### PR TITLE
Update provider to no-fork architecture

### PR DESCRIPTION
**Pull request by m1so**
### Description of your changes

update the provider to use the "no-fork" architecture based on the post shared in [Crossplane #sig-upjet channel](https://crossplane.slack.com/archives/C05T19TB729/p1728488592912289)

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Tested internally in our compositions, which make use of Postgres & RabbitMQ Vault features

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by m1so** [comment]
@jeanduplessis thanks for the update! I completely understand the concerns, however I'm not familiar with Upbound's CI E2E test setup. I managed to fix the E2E setup scripts locally and verified couple of resources via:
```bash
make uptest UPTEST_EXAMPLE_LIST=examples/mount/mount-generic-secrets.yaml
```

we're also running custom build of the provider on our development & staging environments, which make use of `Mounts`, as well as all `database` and `rabbitmq` Vault CRDs (these are however not easy to test in the current setup, as running instance of Postgres and RabbitMQ would need to be provisioned into the KinD cluster)

**Comment by jeanduplessis** [comment]
@m1so ok, we can also accept manual verification results. If you can share screenshots from the tests done showing a successful sync/ready state, we can accept those as well, so you don't have to struggle with Uptest.

**Comment by m1so** [comment]
@jeanduplessis I can share some screenshots from k9s/Vault UI via Crossplane Slack. I also got Uptest working in https://github.com/upbound/provider-vault/pull/46/commits/c01b23e75e88e88e508f50714b601fb585b41b81, however it doesn't run in CI so you'd have to manually verify results via
```bash
make uptest UPTEST_EXAMPLE_LIST=examples/mount/mount-generic-secrets.yaml
```
or other example resources. Alternatively let me know which tests/examples to run and I can post the outputs here

**Review by sergenyalcin — APPROVED** [review]
Thanks @m1so, we synced with @jeanduplessis on this. As he mentioned that we're happy to accept this PR from a technical perspective. Let me also thank you for taking on this complex transition for this provider.

Our only concern was about the tests. As @jeanduplessis said to me, it seems that the results you shared about test results with him were satisfactory.

So, I am approving this PR. Thanks and LGTM!

In release process pov, because two reasons I am proposing to make a major version release for this provider: `v2.0.0`: There is a underlying TF provider major version bump in this change and also the main topic of PR is the no-fork change.

By releasing a major version for this provider, I think we will also provide a better UX for users.

**Comment by sergenyalcin** [comment]
It seems, CI / publish-artifacts (pull_request) fails because of a deprecated action. I will bypass it and merge the PR.

**Pull request merged**
