### PR TITLE
feat(uptest): make uptest usable for repo

### PR DESCRIPTION
**Pull request by haarchri**
### Description of your changes
make uptest usable for repo

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by haarchri** [comment]
/test-examples="examples/auth/authbackend.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/auth/authbackend.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/auth/authbackend.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/genericsecret/genericsecret.yaml,examples/githubauthbackend/githubauthbackend.yaml,examples/githubteam/githubteam.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/genericsecret/genericsecret.yaml,examples/githubauthbackend/githubauthbackend.yaml,examples/githubteam/githubteam.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/auth/authbackend.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/kvsecret/kvsecret.yaml,examples/kvsecretv2/kvsecretv2.yaml,examples/token/token.yaml,examples/tokenauthbackendrole/tokenauthbackendrole.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/mount/mount-generic-secrets.yaml,examples/mount/mount-kv-v1.yaml,examples/mount/mount-kv-v2.yaml"

**Review by jeanduplessis — APPROVED** [review]

**Review by humoflife — COMMENTED** [review]
It would be preferable if uptest can support Go 1.20 or better 1.21, and if we can move versions up versus backwards. golangci-lint would probably stay also at 1.53.3 with go1.20.5 if possible.

Ok to remove unused UPTEST_CLOUD_CREDENTIALS.

The UPTEST_EXAMPLE_LIST drives the e2e tests. Why should they be removed?

Is the hint that the local-dev cluster will remain after tests not useful?

Where should experimental tests reside? Are they not useful for users to experiment with as a foundation for their use cases?

[examples/githubteam/githubteam.yaml](https://github.com/upbound/provider-vault/pull/14/files#diff-e54ca83b57aec959d88a1ee69db78fb566f3ea5908e67c0708795b513fc2a61f) line 25 "manageed" -> "managed"

**Comment by haarchri** [comment]
@humoflife thanks for your comments

> It would be preferable if uptest can support Go 1.20 or better 1.21, and if we can move versions up versus backwards. golangci-lint would probably stay also at 1.53.3 with go1.20.5 if possible.

I didn't know that the PR-triggered comment workflow defaulted to Go version 1.19 for uptest. So, I've submitted a follow-up PR to switch it back to Go version 1.20 -> https://github.com/upbound/provider-vault/pull/16
https://github.com/upbound/uptest/blob/main/.github/workflows/pr-comment-trigger.yml#L13

> The UPTEST_EXAMPLE_LIST drives the e2e tests. Why should they be removed?

We're examining PR comments to create the test example list. When working locally, you can set the ENV variable UPTEST_EXAMPLE_LIST, and we won't have a fixed UPTEST_EXAMPLE_LIST as it'll be rechecked across all the other official providers.

 `UPTEST_EXAMPLE_LIST=examples/kvsecret/kvsecret.yaml,examples/kvsecretv2/kvsecretv2.yaml,examples/token/token.yaml,examples/tokenauthbackendrole/tokenauthbackendrole.yaml make e2e`

https://github.com/upbound/provider-aws/blob/main/Makefile#L190
https://github.com/upbound/provider-gcp/blob/main/Makefile#L185
https://github.com/upbound/provider-azure/blob/main/Makefile#L181

> Is the hint that the local-dev cluster will remain after tests not useful?

In all other providers or configuration repositories, we don't include such a comment when using uptest. From my perspective, it's typical to use the upbound/build module for setting up local development clusters. In our CI process, we delete the cluster after the CI run.

> Where should experimental tests reside? Are they not useful for users to experiment with as a foundation for their use cases?

I believe we have examples generated from the upjet, which people can review to explore experimental versions. 
https://github.com/upbound/provider-vault/tree/main/examples-generated

**Pull request merged**
