### PR TITLE
feat(go): set go 1.20 also for e2e uptest

### PR DESCRIPTION
**Pull request by haarchri**
### Description of your changes
- set go 1.20 also for e2e uptest via https://github.com/upbound/provider-vault/pull/17
- fix typos `manageed` -> `managed` in examples
- switch type `kv-v1` to `kv` because of the following error after first reconcile loop:

```
  # vault_mount.vault-creds-kv1 must be replaced
-/+ resource "vault_mount" "vault-creds-kv1" {
      ~ accessor                     = "kv_425e40b5" -> (known after apply)
      - allowed_managed_keys         = [] -> null
      ~ audit_non_hmac_request_keys  = [] -> (known after apply)
      ~ audit_non_hmac_response_keys = [] -> (known after apply)
      ~ default_lease_ttl_seconds    = 0 -> (known after apply)
      ~ id                           = "kvv1" -> (known after apply)
      - local                        = false -> null
      ~ max_lease_ttl_seconds        = 0 -> (known after apply)
      ~ seal_wrap                    = false -> (known after apply)
      ~ type                         = "kv" -> "kv-v1" # forces replacement
```

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by haarchri** [comment]
/test-examples="examples/mount/mount-generic-secrets.yaml,examples/mount/mount-kv-v1.yaml,examples/mount/mount-kv-v2.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/mount/mount-generic-secrets.yaml,examples/mount/mount-kv-v1.yaml,examples/mount/mount-kv-v2.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/mount/mount-generic-secrets.yaml,examples/mount/mount-kv-v1.yaml,examples/mount/mount-kv-v2.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/mount/mount-generic-secrets.yaml,examples/mount/mount-kv-v1.yaml,examples/mount/mount-kv-v2.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/mount/mount-generic-secrets.yaml,examples/mount/mount-kv-v1.yaml,examples/mount/mount-kv-v2.yaml"

**Comment by haarchri** [comment]
/test-examples="examples/mount/mount-generic-secrets.yaml,examples/mount/mount-kv-v1.yaml,examples/mount/mount-kv-v2.yaml"

**Review by ytsarev — APPROVED** [review]
lgtm

**Pull request merged**
